<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionAviones.BL\GestionAviones.BL.csproj" />
    <ProjectReference Include="..\GestionAviones.DA\GestionAviones.DA.csproj" />
    <ProjectReference Include="..\GestionAviones.Model\GestionAviones.Model.csproj" />
  </ItemGroup>

</Project>
